### ISSUE TITLE
Default SayDialog will drop frames first time italic is called.

### ISSUE THREAD

**Issue by unknowndevice** [FungusGames/Fungus#125] opened 2015-07-28 19:32 UTC
I've noticed that the first time italics is called with the default SayDialog prefab it will lose frames on a build. I think this is happening because "Exo2-Regular" has no italics font packaged.

This error stops happening if you switch to "Amaranth-Regular" which has the italic font bundled.

**Comment by chrisgregan** [comment] 2015-07-30 11:11
Ah I hadn't noticed that before, thanks for pointing it out. Any other ideas for a fix on this one? I guess we could swap it out for a different font that has an italic set included, would mean anyone upgrading to latest version of Fungus would need to set their font references again though. What about changing the Character font setting to Unicode instead of Dyamic - does that have the same problem?

**Comment by movrajr** [comment] 2015-07-30 23:32
My standalone build still has framedrop the first time the dialog is displayed, even after replacing the italic "Exo2-Regular" with normal Arial. In the Editor playback is smooth even though the profiler indicates a 25 ms spike: 14 ms in Block.ExecuteBlock() and 10 ms in Canvas.SendWillRenderCanvases().

**Comment by KumoKairo** [comment] 2015-08-01 07:38
This is some font caching stuff, I usually add a letter or two of every style on an invisible (alpha 0) text component at the start of the scene so it can pre-cache it when the scene is loading.
It's smooth in the editor because it somehow retains cache between Plays

**Comment by movrajr** [comment] 2015-08-01 08:05
@KumoKairo Thanks for that trick, going to try that. I'm not sure if the reason is specifically font caching or just the inefficiency of enabling Canvas objects in general. Whatever the cause, enabling Canvases on startup, making them alpha 0 and fading them in on demand could indeed be the way to go for now.

BTW Unity 5.2, now in beta, introduces UI performance improvements. I was unable to test Fungus in the beta, because Unity crashes when starting the scene. I have submitted a bug report yesterday which Unity QA was able to reproduce.

@chrisgregan Italic Exo 2 is included here: http://www.fontsquirrel.com/fonts/exo-2

**Comment by movrajr** [comment] 2015-08-01 08:44
@KumoKairo Setting all Canvases to use a single font (using Arial for now) and fading in the first one makes my scene smooth, even when toggling the second Canvas. :+1:

**Comment by movrajr** [comment] 2015-08-01 08:55
@KumoKairo I confirm your caching trick works too for a smooth scene with multiple fonts. Downside: there is a noticeable delay between launching the build and the scene starting. I'm going to play around with the font import settings.

**Comment by chrisgregan** [comment] 2015-08-01 21:31
Thanks for the suggestions, gonna try out the 5.2 beta to see if it fixes this issue, if not I'll see if there's a way for Fungus to cache the fonts automatically.

**Comment by movrajr** [comment] 2015-08-01 22:20
Forgot to tell the result of a test project for the 5.2 beta I made earlier today. Added a rotating camera, removed the Flowchart and made a script to enable a custom dialog Canvas by pressing the space bar. When I run the standalone build and press space the scene freezes shortly again. So unfortunately not much has changed in that regard.

@chrisgregan If you're going to check out 5.2 beta, maybe you can see why the editor crashes when there's a Fungus flowchart in the scene and give QA a heads-up. There have been some reports about the beta crashing on scene start in combination with some assets that may be related. For example: http://forum.unity3d.com/threads/constant-crashes-on-play.338596

**Comment by chrisgregan** [comment] 2015-08-11 11:08
Hmmm, looks like I need Unity Pro to access Unity beta versions. :(

Can anyone provide more info on the issue with 5.2 beta? Error messages or screenshots would be very helpful.

**Comment by movrajr** [comment] 2015-08-11 13:59
Last I tried the stuttering was still there in 5.2 beta. Maybe font caching is just something the user is expected to deal with. It's been that way for years: http://answers.unity3d.com/questions/149762/how-to-prepopulate-font-cache.html

As for the crash on playback, that's an issue many people have reported with other assets. Seems to be related to hidden gameobjects. http://forum.unity3d.com/threads/unity-5-2-beta-6-is-available.346422/

**Comment by chrisgregan** [comment] 2015-08-13 14:53
If someone wants to write a Cache Font command I'd be happy to add it in to the library?

For the crash bug, it sounds like we're not doing anything wrong and it's a bug in Unity that they're working to fix. Let's see if it's sorted out in beta 7.

**Comment by movrajr** [comment] 2015-08-17 11:06
Crash bug should be fixed in 5.2f1, will test http://issuetracker.unity3d.com/issues/fungus-flowchart-crashes-unity-5-dot-2

**Comment by chrisgregan** [comment] 2015-08-18 14:41
Awesome - thanks for sending in the bug report!

**Comment by chrisgregan** [comment] 2015-09-02 14:39
I've added the Cache Font command as a requested feature in [Trello](https://trello.com/c/crAeGz9z), and will close this issue.

**Closed by chrisgregan** 2015-09-02 14:39 UTC
